### ISSUE TITLE
Error Reading data - IMA2

### ISSUE THREAD

**Issue by auramilena** [mcanouil/IMA2#1]
Hi, 

I'm trying to use the IMA2 package, but I have the same error in all the files that I try to analyze. I am trying to analyze GEO data from GSE88890, it is a methylation profile using Illumina HumanMethylation450 BeadChip. The methylation file is the one found in the Raw Data (GPL13534_HumanMethylation450_15017482_v.1.1.csv) and the sample file was modified according to the example in IMA2.

However, reading the files generates the following error:

................Reading data................
Error in grep("ILMNID", allcolname):(length(allcolname)) : 
  argument of length 0
In addition: Warning message:
In file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former

Due to this error, I could not do the analysis. I would like to know if you can guide me to solve this error.

I appreciate your kind attention.

Best regards,

Milena Puentes
auramile0926@gmail.com

**Comment by mcanouil** [comment]
Hi,

this error occurs because you don't have a column named "ILMNID" which contains the CpG names for short.
If the csv file is the "standard" csv from GenomeStudio, you can try to rename the column with CpG names to "ILMNID".

IMA2 is not maintained for two reasons: I’m not one of the original authors and now there are plenty of really good packages to do methylation analysis.
So, I recommend you to use packages such as ChAMP or minfi, available on bioconductor.

Best regards,
